# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lh_gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1175, 864)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.Calibration = QtGui.QWidget()
        self.Calibration.setObjectName(_fromUtf8("Calibration"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.Calibration)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.splitter_2 = QtGui.QSplitter(self.Calibration)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.frame = QtGui.QFrame(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.mpl2dwidget = QtGui.QWidget(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl2dwidget.sizePolicy().hasHeightForWidth())
        self.mpl2dwidget.setSizePolicy(sizePolicy)
        self.mpl2dwidget.setMinimumSize(QtCore.QSize(250, 0))
        self.mpl2dwidget.setObjectName(_fromUtf8("mpl2dwidget"))
        self.mpl2dIm = QtGui.QVBoxLayout(self.mpl2dwidget)
        self.mpl2dIm.setObjectName(_fromUtf8("mpl2dIm"))
        self.horizontalLayout.addWidget(self.mpl2dwidget)
        self.mpl1dspec = QtGui.QWidget(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl1dspec.sizePolicy().hasHeightForWidth())
        self.mpl1dspec.setSizePolicy(sizePolicy)
        self.mpl1dspec.setMinimumSize(QtCore.QSize(250, 0))
        self.mpl1dspec.setObjectName(_fromUtf8("mpl1dspec"))
        self.mpl1dSpec = QtGui.QVBoxLayout(self.mpl1dspec)
        self.mpl1dSpec.setObjectName(_fromUtf8("mpl1dSpec"))
        self.horizontalLayout.addWidget(self.mpl1dspec)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_8 = QtGui.QLabel(self.frame)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 0, 0, 1, 1)
        self.colorSlider = QtGui.QSlider(self.frame)
        self.colorSlider.setCursor(QtGui.QCursor(QtCore.Qt.SizeVerCursor))
        self.colorSlider.setOrientation(QtCore.Qt.Vertical)
        self.colorSlider.setObjectName(_fromUtf8("colorSlider"))
        self.gridLayout_4.addWidget(self.colorSlider, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addLayout(self.gridLayout_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.imNumber = QtGui.QLabel(self.frame)
        self.imNumber.setObjectName(_fromUtf8("imNumber"))
        self.horizontalLayout_7.addWidget(self.imNumber)
        self.imSlider = QtGui.QSlider(self.frame)
        self.imSlider.setCursor(QtGui.QCursor(QtCore.Qt.SizeHorCursor))
        self.imSlider.setOrientation(QtCore.Qt.Horizontal)
        self.imSlider.setObjectName(_fromUtf8("imSlider"))
        self.horizontalLayout_7.addWidget(self.imSlider)
        self.imCrop = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imCrop.sizePolicy().hasHeightForWidth())
        self.imCrop.setSizePolicy(sizePolicy)
        self.imCrop.setMinimumSize(QtCore.QSize(150, 0))
        self.imCrop.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.imCrop.setObjectName(_fromUtf8("imCrop"))
        self.horizontalLayout_7.addWidget(self.imCrop)
        self.imInit = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imInit.sizePolicy().hasHeightForWidth())
        self.imInit.setSizePolicy(sizePolicy)
        self.imInit.setMinimumSize(QtCore.QSize(150, 0))
        self.imInit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.imInit.setObjectName(_fromUtf8("imInit"))
        self.horizontalLayout_7.addWidget(self.imInit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.analysisWd = QtGui.QTabWidget(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.analysisWd.sizePolicy().hasHeightForWidth())
        self.analysisWd.setSizePolicy(sizePolicy)
        self.analysisWd.setTabPosition(QtGui.QTabWidget.West)
        self.analysisWd.setTabShape(QtGui.QTabWidget.Rounded)
        self.analysisWd.setElideMode(QtCore.Qt.ElideRight)
        self.analysisWd.setObjectName(_fromUtf8("analysisWd"))
        self.calibration = QtGui.QWidget()
        self.calibration.setObjectName(_fromUtf8("calibration"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.calibration)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.widget_3 = QtGui.QWidget(self.calibration)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setMinimumSize(QtCore.QSize(750, 0))
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.mplSpecCalib = QtGui.QVBoxLayout(self.widget_3)
        self.mplSpecCalib.setObjectName(_fromUtf8("mplSpecCalib"))
        self.horizontalLayout_8.addWidget(self.widget_3)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 9, 0, 1, 2)
        self.label_9 = QtGui.QLabel(self.calibration)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_5.addWidget(self.label_9, 1, 0, 1, 2)
        self.label_10 = QtGui.QLabel(self.calibration)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_5.addWidget(self.label_10, 2, 0, 1, 1)
        self.ref1 = QtGui.QLineEdit(self.calibration)
        self.ref1.setObjectName(_fromUtf8("ref1"))
        self.gridLayout_5.addWidget(self.ref1, 2, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.calibration)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_5.addWidget(self.label_11, 4, 0, 1, 1)
        self.ref2 = QtGui.QLineEdit(self.calibration)
        self.ref2.setObjectName(_fromUtf8("ref2"))
        self.gridLayout_5.addWidget(self.ref2, 4, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.calibration)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_5.addWidget(self.label_12, 6, 0, 1, 1)
        self.ref3 = QtGui.QLineEdit(self.calibration)
        self.ref3.setObjectName(_fromUtf8("ref3"))
        self.gridLayout_5.addWidget(self.ref3, 6, 1, 1, 1)
        self.ref1_slider = QtGui.QSlider(self.calibration)
        self.ref1_slider.setOrientation(QtCore.Qt.Horizontal)
        self.ref1_slider.setObjectName(_fromUtf8("ref1_slider"))
        self.gridLayout_5.addWidget(self.ref1_slider, 3, 0, 1, 2)
        self.ref2_slider = QtGui.QSlider(self.calibration)
        self.ref2_slider.setOrientation(QtCore.Qt.Horizontal)
        self.ref2_slider.setObjectName(_fromUtf8("ref2_slider"))
        self.gridLayout_5.addWidget(self.ref2_slider, 5, 0, 1, 2)
        self.ref3_slider = QtGui.QSlider(self.calibration)
        self.ref3_slider.setOrientation(QtCore.Qt.Horizontal)
        self.ref3_slider.setObjectName(_fromUtf8("ref3_slider"))
        self.gridLayout_5.addWidget(self.ref3_slider, 7, 0, 1, 2)
        self.push_calib = QtGui.QPushButton(self.calibration)
        self.push_calib.setObjectName(_fromUtf8("push_calib"))
        self.gridLayout_5.addWidget(self.push_calib, 8, 0, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem1, 0, 0, 1, 2)
        self.horizontalLayout_8.addLayout(self.gridLayout_5)
        self.analysisWd.addTab(self.calibration, _fromUtf8(""))
        self.timeAnalysis_2 = QtGui.QWidget()
        self.timeAnalysis_2.setObjectName(_fromUtf8("timeAnalysis_2"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.timeAnalysis_2)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.widget_4 = QtGui.QWidget(self.timeAnalysis_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setMinimumSize(QtCore.QSize(500, 0))
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.scanRaw = QtGui.QVBoxLayout(self.widget_4)
        self.scanRaw.setObjectName(_fromUtf8("scanRaw"))
        self.horizontalLayout_9.addWidget(self.widget_4)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_13 = QtGui.QLabel(self.timeAnalysis_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_6.addWidget(self.label_13, 6, 0, 1, 3)
        self.label_14 = QtGui.QLabel(self.timeAnalysis_2)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_6.addWidget(self.label_14, 4, 0, 1, 1)
        self.deltat = QtGui.QLineEdit(self.timeAnalysis_2)
        self.deltat.setObjectName(_fromUtf8("deltat"))
        self.gridLayout_6.addWidget(self.deltat, 4, 1, 1, 2)
        self.ref_substract = QtGui.QCheckBox(self.timeAnalysis_2)
        self.ref_substract.setObjectName(_fromUtf8("ref_substract"))
        self.gridLayout_6.addWidget(self.ref_substract, 2, 0, 1, 3)
        self.ref_onoff = QtGui.QCheckBox(self.timeAnalysis_2)
        self.ref_onoff.setObjectName(_fromUtf8("ref_onoff"))
        self.gridLayout_6.addWidget(self.ref_onoff, 1, 0, 1, 3)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem2, 5, 0, 1, 3)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem3, 3, 0, 1, 3)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem4, 0, 0, 1, 3)
        self.updateGraph = QtGui.QPushButton(self.timeAnalysis_2)
        self.updateGraph.setObjectName(_fromUtf8("updateGraph"))
        self.gridLayout_6.addWidget(self.updateGraph, 9, 0, 1, 3)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem5, 8, 0, 1, 3)
        self.t0_slider = QtGui.QSlider(self.timeAnalysis_2)
        self.t0_slider.setOrientation(QtCore.Qt.Horizontal)
        self.t0_slider.setObjectName(_fromUtf8("t0_slider"))
        self.gridLayout_6.addWidget(self.t0_slider, 7, 0, 1, 3)
        self.horizontalLayout_9.addLayout(self.gridLayout_6)
        self.analysisWd.addTab(self.timeAnalysis_2, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.splitter_2)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.saveScan = QtGui.QPushButton(self.Calibration)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveScan.sizePolicy().hasHeightForWidth())
        self.saveScan.setSizePolicy(sizePolicy)
        self.saveScan.setObjectName(_fromUtf8("saveScan"))
        self.gridLayout.addWidget(self.saveScan, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.tabWidget.addTab(self.Calibration, _fromUtf8(""))
        self.Analysis = QtGui.QWidget()
        self.Analysis.setObjectName(_fromUtf8("Analysis"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.Analysis)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.Analysis)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.refbox = QtGui.QComboBox(self.groupBox)
        self.refbox.setObjectName(_fromUtf8("refbox"))
        self.gridLayout_2.addWidget(self.refbox, 1, 3, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 1, 2, 1, 1)
        self.label_15 = QtGui.QLabel(self.groupBox)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_2.addWidget(self.label_15, 0, 3, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 0, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.groupBox)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_2.addWidget(self.label_16, 0, 6, 1, 1)
        self.normbox = QtGui.QComboBox(self.groupBox)
        self.normbox.setObjectName(_fromUtf8("normbox"))
        self.gridLayout_2.addWidget(self.normbox, 1, 6, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.scanbox = QtGui.QComboBox(self.groupBox)
        self.scanbox.setObjectName(_fromUtf8("scanbox"))
        self.gridLayout_2.addWidget(self.scanbox, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 1, 5, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 1, 4, 1, 1)
        self.scanStore = QtGui.QPushButton(self.groupBox)
        self.scanStore.setObjectName(_fromUtf8("scanStore"))
        self.gridLayout_2.addWidget(self.scanStore, 2, 1, 1, 1)
        self.refStore = QtGui.QPushButton(self.groupBox)
        self.refStore.setObjectName(_fromUtf8("refStore"))
        self.gridLayout_2.addWidget(self.refStore, 2, 3, 1, 1)
        self.normStore = QtGui.QPushButton(self.groupBox)
        self.normStore.setObjectName(_fromUtf8("normStore"))
        self.gridLayout_2.addWidget(self.normStore, 2, 6, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_2)
        self.widget = QtGui.QWidget(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.analysisGraph = QtGui.QVBoxLayout(self.widget)
        self.analysisGraph.setObjectName(_fromUtf8("analysisGraph"))
        self.verticalLayout_6.addWidget(self.widget)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.groupBox_2 = QtGui.QGroupBox(self.Analysis)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_17 = QtGui.QLabel(self.groupBox_2)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_7.addWidget(self.label_17, 0, 0, 1, 3)
        self.label_18 = QtGui.QLabel(self.groupBox_2)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_7.addWidget(self.label_18, 2, 0, 1, 3)
        self.normalizationPre = QtGui.QPushButton(self.groupBox_2)
        self.normalizationPre.setObjectName(_fromUtf8("normalizationPre"))
        self.gridLayout_7.addWidget(self.normalizationPre, 4, 0, 1, 1)
        self.normalizationCan = QtGui.QPushButton(self.groupBox_2)
        self.normalizationCan.setObjectName(_fromUtf8("normalizationCan"))
        self.gridLayout_7.addWidget(self.normalizationCan, 4, 1, 1, 1)
        self.normalizationApp = QtGui.QPushButton(self.groupBox_2)
        self.normalizationApp.setObjectName(_fromUtf8("normalizationApp"))
        self.gridLayout_7.addWidget(self.normalizationApp, 4, 2, 1, 1)
        self.upBoundNorm = QtGui.QSlider(self.groupBox_2)
        self.upBoundNorm.setProperty("value", 99)
        self.upBoundNorm.setOrientation(QtCore.Qt.Horizontal)
        self.upBoundNorm.setObjectName(_fromUtf8("upBoundNorm"))
        self.gridLayout_7.addWidget(self.upBoundNorm, 3, 0, 1, 3)
        self.lowBoundNorm = QtGui.QSlider(self.groupBox_2)
        self.lowBoundNorm.setOrientation(QtCore.Qt.Horizontal)
        self.lowBoundNorm.setObjectName(_fromUtf8("lowBoundNorm"))
        self.gridLayout_7.addWidget(self.lowBoundNorm, 1, 0, 1, 3)
        self.verticalLayout_5.addLayout(self.gridLayout_7)
        self.gridLayout_10.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.Analysis)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_20 = QtGui.QLabel(self.groupBox_3)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_8.addWidget(self.label_20, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.referencePre = QtGui.QPushButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.referencePre.sizePolicy().hasHeightForWidth())
        self.referencePre.setSizePolicy(sizePolicy)
        self.referencePre.setObjectName(_fromUtf8("referencePre"))
        self.gridLayout_8.addWidget(self.referencePre, 2, 0, 1, 1)
        self.upBoundRef = QtGui.QSlider(self.groupBox_3)
        self.upBoundRef.setProperty("value", 99)
        self.upBoundRef.setOrientation(QtCore.Qt.Vertical)
        self.upBoundRef.setObjectName(_fromUtf8("upBoundRef"))
        self.gridLayout_8.addWidget(self.upBoundRef, 1, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_19 = QtGui.QLabel(self.groupBox_3)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_8.addWidget(self.label_19, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lowBoundRef = QtGui.QSlider(self.groupBox_3)
        self.lowBoundRef.setOrientation(QtCore.Qt.Vertical)
        self.lowBoundRef.setObjectName(_fromUtf8("lowBoundRef"))
        self.gridLayout_8.addWidget(self.lowBoundRef, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.referenceApp = QtGui.QPushButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.referenceApp.sizePolicy().hasHeightForWidth())
        self.referenceApp.setSizePolicy(sizePolicy)
        self.referenceApp.setObjectName(_fromUtf8("referenceApp"))
        self.gridLayout_8.addWidget(self.referenceApp, 2, 2, 1, 1)
        self.referenceCan = QtGui.QPushButton(self.groupBox_3)
        self.referenceCan.setObjectName(_fromUtf8("referenceCan"))
        self.gridLayout_8.addWidget(self.referenceCan, 2, 1, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_8)
        self.gridLayout_10.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label = QtGui.QLabel(self.Analysis)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(16777215, 24))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.dateEdit = QtGui.QLineEdit(self.Analysis)
        self.dateEdit.setMaximumSize(QtCore.QSize(16777215, 24))
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.gridLayout_3.addWidget(self.dateEdit, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.Analysis)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 24))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 0, 2, 1, 1)
        self.nameEdit = QtGui.QLineEdit(self.Analysis)
        self.nameEdit.setMaximumSize(QtCore.QSize(16777215, 24))
        self.nameEdit.setObjectName(_fromUtf8("nameEdit"))
        self.gridLayout_3.addWidget(self.nameEdit, 0, 3, 1, 1)
        self.saveButton = QtGui.QPushButton(self.Analysis)
        self.saveButton.setMaximumSize(QtCore.QSize(16777215, 24))
        self.saveButton.setObjectName(_fromUtf8("saveButton"))
        self.gridLayout_3.addWidget(self.saveButton, 0, 4, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_3, 3, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.Analysis)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_23 = QtGui.QLabel(self.groupBox_4)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_9.addWidget(self.label_23, 0, 0, 1, 1)
        self.label_22 = QtGui.QLabel(self.groupBox_4)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_9.addWidget(self.label_22, 0, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.groupBox_4)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_9.addWidget(self.label_21, 0, 2, 1, 1)
        self.axisBox = QtGui.QComboBox(self.groupBox_4)
        self.axisBox.setObjectName(_fromUtf8("axisBox"))
        self.gridLayout_9.addWidget(self.axisBox, 1, 0, 1, 1)
        self.windowLenEdit = QtGui.QLineEdit(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.windowLenEdit.sizePolicy().hasHeightForWidth())
        self.windowLenEdit.setSizePolicy(sizePolicy)
        self.windowLenEdit.setObjectName(_fromUtf8("windowLenEdit"))
        self.gridLayout_9.addWidget(self.windowLenEdit, 1, 1, 1, 1)
        self.windowBox = QtGui.QComboBox(self.groupBox_4)
        self.windowBox.setObjectName(_fromUtf8("windowBox"))
        self.gridLayout_9.addWidget(self.windowBox, 1, 2, 1, 1)
        self.movingPre = QtGui.QPushButton(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.movingPre.sizePolicy().hasHeightForWidth())
        self.movingPre.setSizePolicy(sizePolicy)
        self.movingPre.setObjectName(_fromUtf8("movingPre"))
        self.gridLayout_9.addWidget(self.movingPre, 2, 0, 1, 1)
        self.movingCan = QtGui.QPushButton(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.movingCan.sizePolicy().hasHeightForWidth())
        self.movingCan.setSizePolicy(sizePolicy)
        self.movingCan.setObjectName(_fromUtf8("movingCan"))
        self.gridLayout_9.addWidget(self.movingCan, 2, 1, 1, 1)
        self.movingApp = QtGui.QPushButton(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.movingApp.sizePolicy().hasHeightForWidth())
        self.movingApp.setSizePolicy(sizePolicy)
        self.movingApp.setObjectName(_fromUtf8("movingApp"))
        self.gridLayout_9.addWidget(self.movingApp, 2, 2, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_9)
        self.gridLayout_10.addWidget(self.groupBox_4, 2, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_10)
        self.tabWidget.addTab(self.Analysis, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.widget_2 = QtGui.QWidget(self.tab)
        self.widget_2.setGeometry(QtCore.QRect(30, 40, 581, 701))
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        self.analysisWd.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Geneva analysis", None))
        self.label_8.setText(_translate("MainWindow", "Image level", None))
        self.imNumber.setText(_translate("MainWindow", "0/0", None))
        self.imCrop.setText(_translate("MainWindow", "Crop Image", None))
        self.imInit.setText(_translate("MainWindow", "Reinitialize", None))
        self.label_9.setText(_translate("MainWindow", "Choice of reference wavelength", None))
        self.label_10.setText(_translate("MainWindow", "Reference 1 in eV", None))
        self.label_11.setText(_translate("MainWindow", "Reference 2 in eV", None))
        self.label_12.setText(_translate("MainWindow", "Reference 3 in eV", None))
        self.push_calib.setText(_translate("MainWindow", "Calibrate", None))
        self.analysisWd.setTabText(self.analysisWd.indexOf(self.calibration), _translate("MainWindow", "Spectral calibration", None))
        self.label_13.setText(_translate("MainWindow", "t0 position :", None))
        self.label_14.setText(_translate("MainWindow", "Delta t (s) =", None))
        self.ref_substract.setText(_translate("MainWindow", "Substract reference", None))
        self.ref_onoff.setText(_translate("MainWindow", "Reference taken", None))
        self.updateGraph.setText(_translate("MainWindow", "Update graph", None))
        self.analysisWd.setTabText(self.analysisWd.indexOf(self.timeAnalysis_2), _translate("MainWindow", "Time calbration", None))
        self.saveScan.setText(_translate("MainWindow", "Proceed to analysis", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Calibration), _translate("MainWindow", "Calibration", None))
        self.groupBox.setTitle(_translate("MainWindow", "Graph display", None))
        self.label_4.setText(_translate("MainWindow", "-", None))
        self.label_15.setText(_translate("MainWindow", "Reference", None))
        self.label_7.setText(_translate("MainWindow", "Scan", None))
        self.label_16.setText(_translate("MainWindow", "Normalization", None))
        self.label_3.setText(_translate("MainWindow", "(", None))
        self.label_6.setText(_translate("MainWindow", "/", None))
        self.label_5.setText(_translate("MainWindow", ")", None))
        self.scanStore.setText(_translate("MainWindow", "Store current in Scan", None))
        self.refStore.setText(_translate("MainWindow", "Store current in Reference", None))
        self.normStore.setText(_translate("MainWindow", "Store current in Normalization", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Normalization", None))
        self.label_17.setText(_translate("MainWindow", "Lower bound of integration zone for normalization", None))
        self.label_18.setText(_translate("MainWindow", "Upper bound of integration zone for normalization", None))
        self.normalizationPre.setText(_translate("MainWindow", "Preview", None))
        self.normalizationCan.setText(_translate("MainWindow", "Cancel", None))
        self.normalizationApp.setText(_translate("MainWindow", "Apply", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Reference subtraction", None))
        self.label_20.setText(_translate("MainWindow", "Upper bound for average ref", None))
        self.referencePre.setText(_translate("MainWindow", "Preview", None))
        self.label_19.setText(_translate("MainWindow", "Lower bound for average ref", None))
        self.referenceApp.setText(_translate("MainWindow", "Store reference for display", None))
        self.referenceCan.setText(_translate("MainWindow", "Cancel", None))
        self.label.setText(_translate("MainWindow", "Date", None))
        self.label_2.setText(_translate("MainWindow", "Scan name", None))
        self.saveButton.setText(_translate("MainWindow", "Save Analysis", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Moving average", None))
        self.label_23.setText(_translate("MainWindow", "Axis", None))
        self.label_22.setText(_translate("MainWindow", "Averaging window length", None))
        self.label_21.setText(_translate("MainWindow", "Window type", None))
        self.movingPre.setText(_translate("MainWindow", "Preview", None))
        self.movingCan.setText(_translate("MainWindow", "Cancel", None))
        self.movingApp.setText(_translate("MainWindow", "Apply", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Analysis), _translate("MainWindow", "Analysis", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Plotting", None))
        self.actionOpen.setText(_translate("MainWindow", "open", None))
        self.actionClose.setText(_translate("MainWindow", "close", None))

